import React from 'react';

import './globals.css';

import CMSNavbar from '@/components/cms-navbar';
import MainContainer from '@/components/main-container';

import { Provider } from '@/utils/provider';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js'
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body>
        <Provider>
          <MainContainer>
            <CMSNavbar />
            {children}
          </MainContainer>
        </Provider>
      </body>
    </html>
  );
}
